### PR TITLE
Rebase

### PR DESCRIPTION
**Pull request by pmelange**
Update the fork to the latest from OLSR/olsrd

### CODE REVIEW

**Comment by SvenRoederer** [comment]
Please fix this commit / rebase. caused by this our fork is out of sync ...
> This branch is 1 commit ahead of OLSR:master.

**Comment by pmelange** [comment]
wtf, why didn't a revert work?

**Comment by k-nut** [comment]
If you want to reset to the state before the merge maybe you want to do `reset --hard` to the commit before the merge and then force push that? Not sure if that would be the best way to do this though...

**Comment by pmelange** [comment]
Is this the right way to do it?  Does anyone have another suggestion?

**Comment by pmelange** [comment]
@booo Thanks for helping

**Comment by SvenRoederer** [comment]
> wtf, why didn't a revert work?

even a revert is a commit to the tree, so it will be logged also.

> do reset --hard to the commit before the merge and then force push that?

@k-nut  mentioned, that'S the way I would go

**Pull request merged**
